- name: test my new module
  connection: local
  hosts: localhost
  tasks:
  - name: run the new module
    sacctmgr_qos:
      name: 'hello'
      new: true
    register: testout
  - name: dump test output
    debug:
      msg: '{{ testout }}'
